server:
  port: :8080

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  dbname: go_web

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
jwt:
  secret: xzzxz
  expire: 24h

smtp:
  host: smtp.qq.com
  port: 465
  user: 2538114164@qq.com
  pass: ksohrtxozczeebbc   # SMTP 授权码
  from: 2538114164@qq.com
  from_name: 系统通知
